name: witchcraft-cybersecurity
version: "0.19.0"
summary: Your OPSEC companion
description: |
  **WITCH_CRAFT**

  WITCH_CRAFT is a versatile task automation software designed to serve as the
  foundation for various cybersecurity modules. It provides capabilities for tasks
  such as forensic research, OSINT (Open Source Intelligence), scanning, backup and
  copying, intrusion testing of applications and APIs, and more.

  **Visit the wiki:**

  https://cosmic-zip.github.io/wiki/wiki.html

  **Plugins**

  The Witch_Craft project is extensible through static files and Rust code. Moreover, it is possible to extend its functionalities using `db.json`. This file contains a list of small shell scripts, which means you can integrate anything that interacts with the terminal using ARGS (argsv, readargs(), sys.args(), etc).

  **Note**: There is a Python script called sort.py inside /var/witch_craft/witch_spells/dataset. It is used to create a sorted version of the dataset.

  **Instalation**

  The project initially includes a set of default files. These files
  are created using the best possible data analysis techniques, and
  their final versions are merged into the main project.

  The witch_spells package also provide:

    * Unique Wordlists : _moth_ (16Gb) and _ladybug_ (1Gb)
    * Default Credentials Database
    * IP Geolocation
    * IP Reputation/Score
    * A Set of Social Media Pages for Evil Twin Attacks
    * General Wordlists for Directories and Subdomains
    * MAC Address Vendor Database
    * Usernames Wordlist
    * XSS Wordlist
    * And more, UwU!

grade: stable
confinement: strict
base: core24
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]

parts:
  witchcraft:
    plugin: rust
    source: ./witch_craft
    stage-packages:
      - nmap
      - whois
      - dirb
      - dnsenum
      - libc-bin
      - iproute2
      - xxd
      - iptables
      - coreutils
      - wget
      - curl
      - dnsutils
      - traceroute
      - openssl
      - openssh-server
      - xattr
      - libimage-exiftool-perl
      - tor
      - foremost
      - pkg-config
      - libssl-dev
      - steghide
      - doas
      - nala
      - libwebkit2gtk-4.1-dev
      - build-essential
      - file
      - libxdo-dev
      - 7zip
      - libayatana-appindicator3-dev
      - librsvg2-dev

    spells:
      plugin: nil
      override-build: |
        mkdir -p $SNAPCRAFT_PRIME/var/witch_craft
        cp -R witch_spells $SNAPCRAFT_PRIME/var/witch_craft
      stage:
        - -var
      prime:
        - var

apps:
  witchcraft:
    command: bin/witch_craft
    plugs: [home, network, network-bind, removable-media]
