[package]
name = "witch_craft"
version = "0.17.10"
edition = "2021"

[dependencies]
colored = "2.1.0"
regex = "1.10.6"
reqwest = { version = "0.12.5", features = ["blocking", "json"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"
sha256 = "1.5.0"

[profile.release]
codegen-units = 1
lto = "fat"
panic = "abort"
strip = true
opt-level = "z"

[build]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]
