name: maid-runner
base: core22
version: '0.13.9'
summary: Maid Runner is a companion for cyber security tasks.
description: |
 Maid Runner is a versatile task automation software designed to serve as the foundation for various cyber security modules. It provides capabilities for tasks such as forensic research, OSINT (Open Source Intelligence), scanning, backup and copying, intrusion testing of applications and APIs, and more.
license: GPL-3.0+
architectures:
  - build-on: amd64
grade: devel
confinement: devmode
compression: lzo

layout:
  /var/maid:
    bind: $SNAP/var/maid

parts:
  maid-lists:
    plugin: dump
    source: witch_spells/
    organize:
      "*": /var/maid/
  maid-visual:
    plugin: rust
    rust-channel: "1.70"
    source: witch_oracle/src-tauri/
    build-packages:
      - libwebkit2gtk-4.0-dev 
      - build-essential 
      - libssl-dev 
      - libgtk-3-dev 
      - libayatana-appindicator3-dev 
      - librsvg2-dev
      - cargo
      - rustc
    stage-packages:
      - curl 
      - wget 
      - file
    override-build: |
      cargo build --release
  maid-runner:
    plugin: rust
    source: witch_craft/
    build-packages:
      - build-essential
      - rustc
      - cargo
    stage-packages:
      - p7zip-full 
      - nmap 
      - curl 
      - xxd 
      - libc6 
      - exiftool 
      - traceroute 
      - wget 
      - iproute2 
      - whois 
      - dnsutils 
      - dirb 
      - dnsenum
  maid-api:
      plugin: rust
      source: maid_api/
      build-packages:
        - build-essential
        - rustc
        - cargo

apps:
  maid-runner:
    command: bin/witch_craft
    plugs:
        - home
        - network
  
  maid-visual:
    command: bin/witch_oracle
    plugs:
      - x11
      - wayland

  maid-api:
    command: bin/maid_api

