name: maid-runner
base: core22
version: '0.12.1'
summary: Maid Runner is a companion for cyber security tasks.
description: |
 Maid Runner is a versatile task automation software designed to serve as the foundation for various cyber security modules. It provides capabilities for tasks such as forensic research, OSINT (Open Source Intelligence), scanning, backup and copying, intrusion testing of applications and APIs, and more.

grade: devel
confinement: devmode

parts:
  my-part:
    plugin: nil
