name: witch_craft

on:
  push:
    branches:
      - "trunk"
      - "build"
      - "stable"
  pull_request:
    branches:
      - "*/*"
      - "trunk"
      - "build"
      - "stable"
  schedule:
    - cron: "0 0 * * *" # This schedule runs at midnight every day

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Depedencies
        run: |
          sudo mkdir /var/maid
          sudo cp witch_spells/ /var/maid -R
          sudo chown $(whoami):$(whoami) /var/maid -R
          sudo apt update
          sudo apt install aptitude
          sudo aptitude install -y p7zip-full nmap curl xxd libc6 exiftool traceroute wget iproute2 whois dnsutils dirb dnsenum 
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Uncompress needed files
        run: |
          7z x /var/maid/witch_spells/malware/malware.csv.7z.001
          mv ./full.csv /var/maid/witch_spells/general/malware_hash.bin
      - name: Test Depedencies
        run: nmap --version && curl --version
      - name: Build
        run: cargo build --verbose --manifest-path witch_craft/Cargo.toml
      - name: Run tests
        run: cargo test --verbose --manifest-path witch_craft/Cargo.toml
