name: Rust

on:
  push:
    branches: [ "develop", "build" ]
  pull_request:
    branches: [ "master", "develop", "build" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Deps
      run: |
          sudo mkdir /var/maid
          sudo cp files/ /var/maid -R
          sudo chown $(whoami):$(whoami) /var/maid -R
          sudo apt-get update
          sudo apt-get install -y nmap curl xxd libc6 exiftool traceroute wget iproute2 whois dnsutils dirb dnsenum
    - name: Print Nmap version
      run: nmap --version
    - name: Build
      run: cargo build --verbose --manifest-path maid_runner/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path maid_runner/Cargo.toml
