name: witch_craft

on:
  push:
    branches:
      - "trunk"
      - "build"
      - "stable"
  pull_request:
    branches:
      - "*/*"
      - "trunk"
      - "build"
      - "stable"
  schedule:
    - cron: "0 0 * * *" # This schedule runs at midnight every day

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Depedencies
        run: |
          sudo mkdir -p /var/witch_craft
          sudo cp -r witch_spells/ /var/witch_craft
          sudo chown -R $(whoami):$(whoami) /var/witch_craft
          sudo apt install -y nmap dirb dnsenum libc-bin iproute2 xxd iptables coreutils wget curl dnsutils traceroute
      - name: Build
        run: |
          cargo build --release --manifest-path witch_craft/Cargo.toml
          sudo chmod +x ./witch_craft/target/release/witch_craft
          sudo cp -r ./witch_craft/target/release/witch_craft /bin
      - name: Run tests
        run: cargo test --verbose --manifest-path witch_craft/Cargo.toml
