name: witch_craft

on:
  push:
    branches:
      - "trunk"
      - "main"
      - "stable"
  pull_request:
    branches:
      - "*/*"
      - "trunk"
      - "main"
      - "stable"
  schedule:
    - cron: "0 0 28-31 * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run build.sh
        run: |
          chmod +x build.sh
          sudo ./build.sh
      - name: Build
        run: |
          cargo build --release --manifest-path witch_craft/Cargo.toml
          sudo chmod +x ./witch_craft/target/release/witch_craft
          sudo cp -r ./witch_craft/target/release/witch_craft /bin
      - name: Run tests
        run: cargo test --verbose --manifest-path witch_craft/Cargo.toml
