name: witch_craft

on:
  push:
    branches:
      - "trunk"
      - "build"
      - "stable"
  pull_request:
    branches:
      - "*/*"
      - "trunk"
      - "build"
      - "stable"
  schedule:
    - cron: "0 0 * * *" # This schedule runs at midnight every day

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Depedencies
        run: |
          mkdir -p /var/witch_craft
          cp -r witch_spells/ /var/witch_craft
          chown -R $(whoami):$(whoami) /var/witch_craft
          apt install -y nmap dirb dnsenum ldd xxd iptables ss coreutils wget curl dnsutils traceroute
      - name: Build
        run: cargo build --verbose --manifest-path witch_craft/Cargo.toml
      - name: Run tests
        run: cargo test --verbose --manifest-path witch_craft/Cargo.toml
